middle  Ages s̸o̸ between

w̸h̸i̸c̸h̸ *who* fought

h̸e̸a̸r̸t̸h̸ *heart*

h̸a̸v̸e̸ *has* chosen

with d̸e̸m̸o̸c̸r̸a̸c̸y̸ *democratic values in mind*

every t̸a̸i̸l̸ h̸a̸d̸ *tale has* an  end

k̸i̸l̸l̸e̸d̸ *attempted to kill* him  and b̸e̸ i̸n̸j̸u̸r̸e̸d̸ *only succeeded in injuring him*

in  which o̸n̸e̸ he

by s̸o̸m̸e̸ a̸u̸t̸h̸o̸r̸ l̸i̸k̸e̸ Mr  Malory f̸o̸r̸ e̸x̸a̸m̸p̸l̸e̸ *and other authors*

w̸a̸s̸ a̸l̸s̸o̸ p̸a̸i̸n̸t̸e̸d̸ *is depicted*

