during  a *whole* week
d̸u̸r̸i̸n̸g̸ a̸ *last* week

w̸h̸o̸ *which* has  arms

w̸h̸o̸ f̸a̸i̸l̸l̸e̸d̸ *which failed*

This  robot u̸s̸e̸ *uses*

h̸i̸s̸ *its* portable

help  us a̸l̸l̸ *in many of* our

another *pair of* hands

h̸e̸l̸p̸s̸ a̸n̸d̸ t̸e̸a̸c̸h̸e̸s̸ *help an teach* us i̸n̸ something

n̸e̸c̸e̸s̸s̸i̸t̸e̸s̸ *necessitates*

c̸o̸n̸c̸l̸u̸n̸d̸e̸ *conclude*

s̸c̸i̸e̸n̸t̸s̸ *scientists*

a̸n̸d̸ *in* answer  to  our

verbal *commands* and b̸o̸d̸y̸ a̸c̸t̸i̸o̸n̸s̸ *bodily gestures*

