science o̸r̸ h̸u̸m̸a̸n̸i̸t̸y̸ *and humanities*

t̸r̸a̸d̸i̸t̸i̸o̸n̸n̸a̸l̸ *traditional*

d̸o̸m̸i̸n̸a̸t̸e̸s̸ *was preponderant*

c̸o̸m̸p̸o̸s̸e̸ *composed* by

g̸r̸e̸a̸t̸s̸ *grand* parents

s̸h̸o̸w̸s̸ *captures* the  image
_[vocabulary]_

document n̸a̸m̸e̸d̸ *titled*

married a̸n̸ y̸o̸u̸n̸g̸e̸r̸ *at a young* age

that a̸t̸ before

I'll  explain *to* you
_[je vous explique = I explain to you]_

*the situation of* women s̸i̸t̸u̸a̸t̸i̸o̸n̸

gets i̸m̸p̸r̸o̸v̸e̸ *improved*

e̸n̸t̸i̸t̸l̸e̸d̸ 'Suffragette' *made* by  Sarah  Gavon d̸a̸t̸i̸n̸g̸ b̸a̸c̸k̸ t̸o̸ *in* 2015

harassment o̸r̸ *and* the

f̸i̸n̸a̸l̸l̸y̸ she  became

to e̸x̸p̸l̸a̸i̸n̸ v̸e̸r̸y̸ s̸h̸o̸r̸t̸y̸ a̸b̸o̸u̸t̸ *give a brief description of* the

the  society d̸i̸d̸n̸'̸t̸ c̸o̸n̸s̸i̸d̸e̸r̸ t̸h̸e̸m̸ *spurned their demands*

their  fight t̸o̸d̸a̸y̸

p̸r̸e̸s̸e̸n̸t̸s̸ *showcases*
_[vocabulary]_

a̸n̸d̸ m̸e̸a̸n̸s̸ that  when  it

than m̸a̸l̸e̸-̸t̸e̸a̸m̸ *a male-only team*

t̸h̸e̸ half  of

*whether* they  work  for

this  equality *still* has  to  face s̸t̸i̸l̸l̸ discrimination

g̸e̸t̸t̸i̸n̸g̸ b̸e̸t̸t̸e̸r̸ *improving*

h̸a̸d̸ *has* been  redefined

But *there's a vestigial sexual discrimination* still t̸h̸e̸r̸e̸'̸r̸e̸ l̸o̸t̸ o̸f̸ s̸o̸c̸i̸a̸l̸ d̸i̸f̸f̸e̸r̸e̸n̸c̸e̸ n̸o̸w̸a̸d̸a̸y̸s̸ *present*

m̸e̸n̸t̸a̸l̸i̸t̸i̸e̸s̸ *mindset*
