give  faith  and *instill* fear

W̸h̸e̸r̸e̸a̸s̸ *However*

g̸e̸t̸ c̸h̸a̸n̸g̸e̸d̸ *is set* in  the  right

H̸e̸r̸o̸e̸s̸ a̸l̸s̸o̸ s̸t̸i̸l̸l̸ *Even heroes* face

T̸h̸e̸y̸ a̸r̸e̸ l̸i̸k̸e̸ *Like* us,  they  have

t̸a̸k̸e̸ a̸ w̸a̸y̸ *follow the right path* to  avoid

s̸u̸c̸c̸e̸e̸d̸s̸ o̸n̸ *succeeded in* his

that h̸a̸p̸p̸e̸n̸ *happened* in  her

s̸t̸a̸r̸t̸ *started* to  work

after *that* she

T̸h̸e̸r̸e̸ t̸h̸o̸s̸e̸ *Those* two

all  our  daily p̸r̸o̸b̸l̸e̸m̸ *problems*

a̸r̸e̸ a̸l̸s̸o̸ p̸e̸r̸s̸o̸n̸ w̸h̸o̸ want  to

w̸h̸i̸c̸h̸ s̸t̸a̸r̸t̸ *who started* to  listen

first  king  who i̸n̸t̸r̸o̸d̸u̸c̸e̸ *introduced* it
first  king w̸h̸o̸ *to* introduce  it

h̸a̸v̸e̸ *had* to  face

M̸a̸n̸ *Men* and W̸o̸m̸a̸n̸ *women*

c̸r̸e̸a̸t̸e̸ *created* and p̸o̸s̸s̸e̸s̸s̸ *possessed*

are d̸i̸f̸f̸e̸r̸e̸n̸t̸ f̸r̸o̸m̸ *not tied to* the  culture

a̸w̸a̸r̸n̸e̸s̸s̸ *awareness*

m̸a̸k̸e̸ u̸s̸ better *ourselves*

to b̸e̸ *become* better

gets w̸i̸n̸d̸e̸d̸ *sidetracked* by i̸n̸t̸e̸r̸e̸s̸t̸i̸n̸g̸ *shifting* her *interest* on  the

her  life  inspires o̸t̸h̸e̸r̸ *others*

authors r̸i̸g̸h̸t̸s̸ *write* books

follow h̸e̸r̸e̸ *her* example

to  take  her f̸o̸r̸ a̸n̸ e̸x̸a̸m̸p̸l̸e̸ *as a role model*

