*is* tasty

food *is* tasty

b̸u̸y̸ *court* somebody t̸o̸ s̸t̸a̸y̸ w̸i̸t̸h̸... *in* *view* *of* *obtaining* *sexual* *favours*
[𝑏𝑒𝑑 𝑖𝑠 𝑐𝑟𝑢𝑑𝑒]

b̸i̸g̸ *luxurious* *underwater* house u̸n̸d̸e̸r̸ w̸a̸t̸e̸r̸

c̸a̸l̸l̸ *name* it Chickenland
c̸a̸l̸l̸ *baptize* it Chickenland

S̸D̸F̸ *homeless* *persons,* *paupers*

give money f̸o̸r̸ *to* our ... *family*
g̸i̸v̸e̸ m̸o̸n̸e̸y̸ f̸o̸r̸ *assist* our ... *family* *financially*

p̸u̸t̸ *invest* the r̸e̸s̸t̸ t̸o̸ t̸h̸e̸ B̸a̸n̸k̸ *remaining* *amount* *wisely*

That's all *folks*

