news *and* written

'̸s̸ *is* the

w̸h̸a̸t̸'̸s̸ *what* a  biohacker *is*

'̸s̸ *has* a  modified

important  than  other b̸o̸d̸y̸. *parts of the body*
i̸s̸ i̸m̸p̸o̸r̸t̸a̸n̸t̸ t̸h̸a̸n̸ *supersedes* other b̸o̸d̸y̸. *bodily functions*

t̸o̸u̸g̸h̸t̸s̸ *thoughts*

p̸i̸o̸n̸e̸r̸ *pioneer*

his s̸e̸l̸f̸ e̸x̸p̸e̸r̸i̸m̸e̸n̸t̸s̸ h̸a̸s̸ *self-experiments have*

gone w̸r̸o̸n̸g̸ *awry*
_[vocabulary]_

b̸e̸ *being* able

c̸h̸a̸n̸g̸e̸ *modify* genes

g̸e̸t̸ *getting* a  genetic

t̸h̸e̸y̸'̸r̸e̸ *there are* risks

Lee w̸a̸n̸t̸ *wants* to  see

b̸i̸o̸l̸o̸g̸i̸c̸a̸l̸y̸ *biologically*
