t̸e̸c̸h̸n̸o̸l̸o̸g̸i̸c̸ *technological*

about  him a̸f̸t̸e̸r̸ *later*
_[after something]_

d̸e̸v̸e̸l̸o̸p̸ a̸ *has developed*

c̸o̸m̸p̸l̸e̸t̸l̸y̸ *completely*

c̸o̸n̸t̸r̸o̸l̸l̸ *control*

'̸r̸e̸ *are*

h̸u̸m̸a̸n̸s̸ *human* errors

d̸u̸ *due* to

this  project s̸o̸l̸v̸e̸ *solves*

c̸o̸n̸t̸r̸e̸l̸l̸e̸d̸ *controlled*

s̸a̸t̸e̸l̸i̸t̸e̸ *satellite*

the  world  the s̸h̸i̸p̸s̸ *ship is*

c̸u̸r̸s̸e̸ *cruise*

secure *and cost-effective*
