i̸d̸e̸a̸ *concept* of

answer t̸o̸ this

w̸e̸'̸r̸e̸ *I am* going  to

traditional a̸n̸d̸ o̸l̸d̸

w̸e̸'̸l̸l̸ *I'll*

*the evolution of* families  and  societies e̸v̸o̸l̸u̸t̸i̸o̸n̸

T̸r̸a̸d̸i̸t̸i̸o̸n̸n̸a̸l̸ a̸n̸d̸ p̸a̸s̸t̸ *Traditional* society

s̸h̸o̸w̸ *shows* the  image

are g̸a̸t̸h̸e̸r̸i̸n̸g̸ *gathered*

s̸e̸e̸m̸ *seems* to  be

w̸e̸a̸r̸i̸e̸d̸ *wears*
_[wearied = tired]_

s̸e̸r̸v̸e̸d̸ *serves*

f̸o̸u̸r̸t̸y̸s̸ *forties*

at t̸h̸e̸ *an* younger  age

w̸a̸s̸ headed

g̸e̸t̸ *gets* reflected

F̸a̸m̸i̸l̸i̸e̸s̸ *The evolution of families* and  societies e̸v̸o̸l̸u̸t̸i̸o̸n̸

r̸i̸g̸h̸t̸ *rights* for

f̸l̸i̸g̸h̸t̸e̸d̸ *fought*

w̸o̸m̸e̸n̸ *women's* right

s̸t̸a̸r̸t̸ *started* to

l̸e̸a̸d̸ *led* by

a̸r̸r̸e̸s̸t̸m̸e̸n̸t̸ *harassment*

w̸h̸a̸t̸'̸s̸ *about* the

composed  of w̸o̸m̸a̸n̸ *women*

w̸o̸m̸a̸n̸'̸s̸ *women's*

a̸l̸l̸ c̸o̸u̸n̸t̸r̸y̸ *most countries*

there h̸a̸s̸ *is* still

than m̸a̸l̸e̸ *a male-only* team

*company* boss c̸o̸m̸p̸a̸n̸y̸

g̸e̸t̸s̸ *is getting* better

had *been* established

g̸e̸t̸ *got* worse

e̸r̸a̸s̸e̸ *eradicate* these  differences
