give faith and *command* fear

inspires o̸t̸h̸e̸r̸ *others*

these values *in* *order* to be a

s̸c̸h̸o̸l̸a̸r̸ s̸h̸i̸p̸ *scholarship*

succeeds o̸n̸ *in* creating

that s̸o̸m̸e̸ can influence people

same values l̸i̸k̸e̸ *as* King Arthur

Rosenberg bases h̸i̸s̸ *her* analysis

g̸o̸t̸ *pondered* many questions

make us t̸h̸i̸n̸k̸i̸n̸g̸ *think*

with s̸o̸m̸e̸ *commendable* values

or a̸ political groups

his d̸e̸a̸t̸h̸ *demise* came upon

and t̸h̸e̸n̸ when

