d̸e̸a̸l̸ w̸i̸t̸h̸ *elaborate on* the n̸o̸t̸i̸o̸n̸ *subject*

e̸q̸u̸a̸l̸ *egalitarian* king

sitting t̸o̸ *around* that  table

who l̸i̸s̸t̸e̸n̸ *listened* to  his

W̸e̸ *He* did  not  have

famous  knight *known* for  his

b̸e̸c̸a̸u̸s̸e̸ according

*media* icon o̸f̸ t̸h̸e̸ m̸e̸d̸i̸a̸

got e̸a̸r̸l̸y̸ a  job
got *an* early a̸ job

t̸h̸i̸s̸ *her* entry

l̸o̸t̸s̸ o̸f̸ a̸w̸a̸r̸d̸ *many awards*

s̸t̸r̸e̸n̸g̸t̸h̸ *strong* woman

an i̸n̸f̸l̸u̸e̸n̸t̸ *influential* woman

l̸i̸k̸e̸ *and* king

are  charismatic c̸h̸a̸r̸a̸c̸t̸e̸r̸ *characters*

to a̸c̸c̸o̸m̸p̸l̸i̸s̸h̸e̸d̸ *accomplish*

a̸t̸ *to* the  rank  of t̸h̸e̸ heroes

*if* they  just  accomplished

b̸y̸ t̸h̸i̸s̸ w̸a̸y̸ i̸n̸s̸p̸i̸r̸e̸ *thereby inspiring*

They c̸r̸e̸a̸t̸e̸d̸ *can create* new c̸o̸n̸c̸e̸p̸t̸ *concepts* that s̸o̸m̸e̸ i̸n̸f̸l̸u̸e̸n̸c̸e̸d̸ *can influence* people f̸o̸l̸l̸o̸w̸e̸d̸ to i̸n̸c̸r̸e̸a̸s̸e̸ t̸h̸e̸ l̸i̸f̸e̸ *better their lives* in  our s̸o̸c̸i̸e̸t̸y̸ *society.*

s̸o̸ created

intelligence a̸ *and* strength

h̸a̸s̸ *had* children *of her own*

period o̸n̸ *of* her

l̸i̸f̸e̸s̸ *lives*

w̸a̸n̸t̸s̸ *want to* look  like

by s̸o̸m̸e̸ a̸u̸t̸h̸o̸r̸ l̸i̸k̸e̸ Mr  Malory f̸o̸r̸ e̸x̸a̸m̸p̸l̸e̸ *and other authors*

they i̸n̸f̸l̸u̸e̸n̸c̸e̸d̸ *influence* the  mind

a̸d̸u̸l̸t̸ *both adults* and  children a̸l̸s̸o̸

