*the* Clayton  Case

Lana C̸l̸a̸y̸t̸o̸n̸, 5̸2̸, *Clayton (a* nurse K̸i̸l̸l̸e̸d̸ *aged 52) killed*

in  the v̸i̸c̸t̸i̸m̸s̸ f̸o̸o̸d̸(̸s̸)̸ *victim's food* and  drinks  by  Lana *unbeknownst to the victim*

h̸a̸v̸e̸ *was having* an  affair

she a̸l̸s̸o̸ n̸e̸e̸d̸e̸d̸ *was in desperate need of* some  money

t̸h̸e̸i̸r̸ *Their* house ... s̸i̸n̸g̸l̸e̸ l̸a̸d̸y̸ *and her husband's life insurance may have acted as a tantalizing temptation to the lady.*

s̸c̸h̸o̸k̸e̸d̸ *shocked*

h̸e̸r̸ *his* family

m̸i̸s̸s̸u̸s̸e̸d̸ *misused*

that's t̸h̸e̸ t̸h̸i̸n̸k̸ w̸h̸i̸c̸h̸ m̸a̸k̸e̸ *what prompted* me *to* choose  this  news
