𝘁𝗵𝗲 Clayton Case

Lana C̸l̸a̸y̸t̸o̸n̸, 5̸2̸, C𝗹𝗮𝘆𝘁𝗼𝗻 (𝗮 nurse K̸i̸l̸l̸e̸d̸ 𝗮𝗴𝗲𝗱 52) 𝗸𝗶𝗹𝗹𝗲𝗱

in the v̸i̸c̸t̸i̸m̸s̸ f̸o̸o̸d̸(̸s̸)̸ 𝘃𝗶𝗰𝘁𝗶𝗺'𝘀 𝗳𝗼𝗼𝗱 and drinks by Lana 𝘂𝗻𝗯𝗲𝗸𝗻𝗼𝘄𝗻𝘀𝘁 𝘁𝗼 𝘁𝗵𝗲 𝘃𝗶𝗰𝘁𝗶𝗺

h̸a̸v̸e̸ 𝘄𝗮𝘀 𝗵𝗮𝘃𝗶𝗻𝗴 an affair

she a̸l̸s̸o̸ n̸e̸e̸d̸e̸d̸ 𝘄𝗮𝘀 𝗶𝗻 𝗱𝗲𝘀𝗽𝗲𝗿𝗮𝘁𝗲 𝗻𝗲𝗲𝗱 𝗼𝗳 some money

t̸h̸e̸i̸r̸ T𝗵𝗲𝗶𝗿 house ... s̸i̸n̸g̸l̸e̸ l̸a̸d̸y̸ 𝗮𝗻𝗱 𝗵𝗲𝗿 𝗵𝘂𝘀𝗯𝗮𝗻𝗱'𝘀 𝗹𝗶𝗳𝗲 𝗶𝗻𝘀𝘂𝗿𝗮𝗻𝗰𝗲 𝗺𝗮𝘆 𝗵𝗮𝘃𝗲 𝗮𝗰𝘁𝗲𝗱 𝗮𝘀 𝗮 𝘁𝗮𝗻𝘁𝗮𝗹𝗶𝘇𝗶𝗻𝗴 𝘁𝗲𝗺𝗽𝘁𝗮𝘁𝗶𝗼𝗻 𝘁𝗼 𝘁𝗵𝗲 𝗹𝗮𝗱𝘆.

s̸c̸h̸o̸k̸e̸d̸ 𝘀𝗵𝗼𝗰𝗸𝗲𝗱

h̸e̸r̸ 𝗵𝗶𝘀 family

m̸i̸s̸s̸u̸s̸e̸d̸ 𝗺𝗶𝘀𝘂𝘀𝗲𝗱

that's t̸h̸e̸ t̸h̸i̸n̸k̸ w̸h̸i̸c̸h̸ m̸a̸k̸e̸ 𝘄𝗵𝗮𝘁 𝗽𝗿𝗼𝗺𝗽𝘁𝗲𝗱 me 𝘁𝗼 choose this news

