s̸c̸i̸e̸n̸c̸e̸ *scientific* creation

to *a* web  article

c̸r̸e̸a̸t̸i̸o̸n̸, *creation.*

created ... f̸o̸r̸ t̸h̸e̸ *a fully autonomous forms* two l̸a̸s̸t̸ years *ago*
created ... *a fully autonomous farm that functioned without human intervention* for  the *last* two l̸a̸s̸t̸ years

s̸u̸c̸c̸e̸d̸ t̸o̸ c̸r̸e̸a̸t̸e̸ *succeeded in creating*

w̸i̸t̸c̸h̸ *which*

m̸a̸k̸e̸ g̸r̸o̸w̸i̸n̸g̸ u̸p̸ *cultivate*

i̸t̸ i̸s̸n̸'̸t̸ h̸u̸m̸a̸n̸ t̸h̸a̸t̸ *people don't* tend ... *these plants but* robots *do.*

26000 p̸l̸a̸n̸t̸ *plants*

i̸n̸ a̸ y̸e̸a̸r̸ *annually*
_(to show that they are dreaming a bright future)_

m̸i̸x̸ *blend*

w̸a̸n̸t̸s̸ *intends* to

*brand* new  technologies
_(show off vocabulary)_

o̸l̸d̸ *age-old* tradition
_(show off vocabulary)_

to s̸a̸l̸e̸ *sell*

t̸o̸ *at the price of* 5  million
*amounting* to  5  million

scientists a̸n̸ f̸a̸r̸m̸e̸r̸ *and farmers*

h̸a̸d̸ w̸o̸r̸k̸ t̸o̸g̸e̸t̸h̸e̸r̸ *have collaborated*

T̸h̸e̸s̸e̸ *This* farm  is

to t̸h̸e̸s̸e̸ *this* project

l̸a̸k̸e̸ *lack* of  water

w̸h̸e̸n̸ *whenever* they  want

to p̸u̸s̸h̸ b̸a̸c̸k̸ ... f̸o̸r̸ e̸x̸a̸m̸p̸l̸e̸ *abstract away from agriculture problems like lack of water and inclement weather*
