save o̸t̸h̸e̸r̸ *others*

against d̸e̸v̸i̸l̸ *the* *evil*

different p̸e̸r̸i̸o̸d̸ *periods*

t̸h̸e̸ *they* improve

h̸e̸a̸r̸t̸h̸ *heart*

to his k̸i̸n̸g̸d̸o̸m̸ *people*



s̸o̸ during

r̸e̸w̸a̸r̸d̸s̸ *award*

s̸t̸r̸e̸n̸g̸t̸h̸ *strong* woman

from t̸h̸e̸ scratch

s̸t̸a̸r̸t̸ *started* to fight

i̸n̸c̸r̸e̸a̸s̸i̸n̸g̸ *growth* of the literature

the s̸e̸l̸l̸i̸n̸g̸ *sales* *of* some books

extraordinary f̸a̸c̸t̸ *feats*

q̸u̸a̸l̸i̸f̸i̸e̸d̸ t̸h̸e̸ *qualify* *as* heroes

t̸h̸e̸ superheroes

Some p̸s̸y̸c̸h̸o̸l̸o̸g̸i̸s̸t̸ u̸s̸e̸s̸ *psychologists* *use*

she g̸r̸o̸w̸s̸ *grew* up and h̸a̸v̸e̸ *has* children

g̸e̸t̸ *got* widened

learn o̸f̸ *from* them

to e̸v̸e̸r̸y̸o̸n̸e̸ *anyone*

and b̸e̸ *was* injured

when t̸h̸e̸y̸ *we* need them

society c̸r̸e̸a̸t̸e̸ m̸y̸t̸h̸ *creates* *myths*

where they *were* born

be aware *of* the difference

